/**
 * G1-TEMPLATE — the deterministic CC-plugin renderer (the "compiler").
 *
 * SSOT: docs/design/agent-skill-compile-domain-model.md §4 (the compiled artifact,
 *       3-tier progressive disclosure) + Inv II (additive projection over the Floor)
 *       + Inv VI (auth/invoke core deterministically TEMPLATED, never LLM-authored),
 *       ADR-6/ADR-8; and docs/design/cc-plugin-artifact-spec.md §1/§2/§3/§5.
 *
 * WHAT THIS IS — a pure, deterministic function (NO LLM, no network, no clock unless
 * you let it) that projects a *granted cap-set* into a ready-to-install Claude Code
 * plugin directory. Given the same (Floor + capabilityIds + agentId + code +
 * compileStamp) it emits BYTE-IDENTICAL files. It is `renderPlugin()` (returns the
 * files in memory) + `writePlugin()` (materializes them to a dir, with modes). D1-
 * ENDPOINT imports this to serve `GET /integration/<agent>`.
 *
 * THE SKELETON IT EMITS (annotated per cc-plugin-artifact-spec §5):
 *
 *   plexus@<agentId>/                       # a self-hosting one-plugin marketplace
 *   ├── .claude-plugin/
 *   │   ├── plugin.json          [T]        # identity; version = compile stamp (cache key, ADR-10)
 *   │   └── marketplace.json     [T]        # makes the dir `claude plugin marketplace add`-able
 *   ├── skills/use-plexus/
 *   │   └── SKILL.md             [P]+[T]    # tier-1 frontmatter [T] + tier-2 prose body [P]
 *   ├── bin/
 *   │   └── plexus               [S]        # tier-3: G2 engine VERBATIM (auth core, never in context)
 *   ├── install.sh               [T]        # one-command install; code rides via env->0600 scratch
 *   └── README.md                [S]        # human doc (NOT loaded as CC context — D1)
 *
 * INV VI (templated auth core, never LLM-authored) — the entire redeem->PAT->
 * handshake->token->invoke chain is `bin/plexus`, which is the COMMITTED, Floor-driven
 * G2 engine copied BYTE-FOR-BYTE (see `readEngine()`), plus the templated `install.sh`
 * whose enrollment step invokes that same engine. No prose file carries auth mechanics;
 * the SKILL body [P] is pedagogy only. Nothing here is generated by a model.
 *
 * INV III / secret hygiene — NO long-lived secret is ever written into the artifact.
 * The durable PAT never appears. The one-time enrollment code is NOT baked into any
 * emitted file; it rides the *install command string* (returned separately) in an env
 * var, which `install.sh` lands in a 0600 scratch file, redeems, then deletes.
 */

import { fileURLToPath } from "node:url";
import { readFileSync, mkdirSync, writeFileSync, chmodSync } from "node:fs";
import { join, dirname } from "node:path";

import type { WellKnownDocument, CapabilitySummary, CapabilityId } from "@plexus/protocol";
import {
  shSingleQuote,
  stripSlash,
  requireNonEmpty,
  stripOneTrailingNewline,
  assertSafeAgentId,
  assertNoHeredocCollision,
} from "./shell-util.ts";

// ── Fixed identity constants (kebab-case; the skill namespace + install target) ──────
// The plugin NAME stays the stable "plexus" so the skill is `/plexus:use-plexus` and the
// verified install command is `plexus@plexus` (`<plugin>@<marketplace>`). Per-agent
// identity is carried by the DIRECTORY name (plexus@<agentId>), the version (compile
// stamp), and the description — NOT by the plugin name (an `@` in the name would break
// `claude plugin install <plugin>@<marketplace>` parsing). See cc-plugin-artifact-spec §5.
const PLUGIN_NAME = "plexus";
const MARKETPLACE_NAME = "plexus";
const SKILL_NAME = "use-plexus";
const AUTHOR_NAME = "Plexus";

/**
 * The per-agent, collision-proof launcher COMMAND name (`plexus-<agentId>`). This is the ONE
 * command the SKILL teaches the agent to type. Being unique per agentId, it can NEVER be shadowed
 * on the Bash PATH by a global `plexus` (a different project's/version's binary) or by another
 * agent's plugin — the exact failure the bare `plexus` had. It execs THIS plugin's OWN bundled,
 * version-pinned engine (the sibling `bin/plexus`) by a path relative to itself, binding identity
 * via `PLEXUS_AGENT_ID` so calls authenticate as this agent and no other. (agentId is already
 * filename-safe: it names the `plexus@<agentId>` dir and the `<agentId>.pat` self-store.)
 */
function launcherCommand(agentId: string): string {
  return `plexus-${agentId}`;
}

// The G2 engine SSOT — copied verbatim into the artifact's `bin/plexus` (tier-3). Resolved
// relative to this module the same way the runtime references its other repo assets
// (see core/admin.ts). Overridable for tests.
const ENGINE_SOURCE = fileURLToPath(new URL("../../../../tools/plexus-cli/plexus", import.meta.url));
// The hand-authored [P] prose body of the SKILL (same for every integration).
const SKILL_BODY_SOURCE = fileURLToPath(new URL("./templates/skill-body.md", import.meta.url));

// ── Public API ───────────────────────────────────────────────────────────────────────

/** Inputs to the renderer — the Floor + a selected cap-set + who + the bootstrap code. */
export interface RenderPluginInput {
  /** The gateway's Floor: `GET /.well-known/plexus`. Source of gateway URL + cap metadata. */
  floor: WellKnownDocument;
  /**
   * The selected (granted) cap-set to project — capability ids. MUST be a subset of the
   * Floor's advertised capabilities (a cap the Floor does not advertise cannot be granted
   * or referenced). Order is irrelevant; the renderer sorts for determinism.
   */
  capabilityIds: CapabilityId[];
  /** The agent this integration is compiled for (the enrollment/PAT identity). */
  agentId: string;
  /** The one-time enrollment code (`plx_enroll_…`). Rides the install command, never a file. */
  enrollmentCode: string;
  /**
   * The compile timestamp — the ONLY intentional source of non-determinism, injected so
   * tests are stable. Any ISO-ish string; defaults to now. Drives the plugin `version`
   * (the cache key, ADR-10) so a regenerated artifact is seen as a new version.
   */
  compileStamp?: string;
  /** Override the G2 engine source path (tests only). Defaults to `tools/plexus-cli/plexus`. */
  enginePath?: string;
  /** Override the [P] skill-body source path (tests only). */
  skillBodyPath?: string;
}

/** One emitted file, with its POSIX mode (executables are 0o755, the rest 0o644). */
export interface RenderedFile {
  /** Path relative to the plugin root (e.g. `.claude-plugin/plugin.json`). */
  path: string;
  content: string;
  mode: number;
}

/** The rendered artifact — files in memory + the copy-able install command carrying the code. */
export interface RenderedPlugin {
  /** The artifact directory name (`plexus@<agentId>`). */
  dirName: string;
  /** The plugin name field (`plexus`) — the skill namespace + install target. */
  pluginName: string;
  /** The marketplace name (`plexus`). */
  marketplaceName: string;
  /** The plugin version = the compile stamp (the cache key). */
  version: string;
  /** All emitted files, in a deterministic order. */
  files: RenderedFile[];
  /**
   * The copy-able ONE-COMMAND install string the admin console shows (ADR-8). It carries
   * the one-time code in an ENV var (never baked into an artifact file). D1-ENDPOINT may
   * adapt the URL; the shape is `curl … | PLEXUS_ENROLL_CODE=… bash`.
   */
  installCommand: string;
}

/**
 * Render the plugin artifact deterministically. Pure w.r.t. its inputs (given a
 * `compileStamp`, the output is byte-identical across runs, machines, and clocks).
 */
export function renderPlugin(input: RenderPluginInput): RenderedPlugin {
  // agentId flows into shell comments + curl URLs + a `plexus@<id>` dir path; REFUSE any id that
  // is not a safe slug so no interpolation point can inject a live shell line (defense-in-depth
  // behind the connect-time check). See shell-util.assertSafeAgentId.
  const agentId = assertSafeAgentId(input.agentId);
  const code = requireNonEmpty(input.enrollmentCode, "enrollmentCode");
  const stamp = input.compileStamp ?? new Date().toISOString();
  const version = versionFromStamp(stamp);
  const gatewayBaseUrl = stripSlash(requireNonEmpty(input.floor?.gateway?.baseUrl, "floor.gateway.baseUrl"));

  // Resolve the selected cap-set against the Floor. Every requested id MUST be advertised
  // (Inv II: a skill references ONLY caps the Floor knows — the build-time verifier's core
  // guarantee, enforced here by construction). Sorted by id for a stable ordering.
  const caps = resolveCaps(input.floor.capabilities ?? [], input.capabilityIds);

  const dirName = `${PLUGIN_NAME}@${agentId}`;

  const engine = readFileSync(input.enginePath ?? ENGINE_SOURCE, "utf8");
  const skillBody = readFileSync(input.skillBodyPath ?? SKILL_BODY_SOURCE, "utf8");

  // The plugin's payload files (everything EXCEPT install.sh). install.sh is the SELF-CONTAINED
  // bootstrap: it inlines EVERY one of these verbatim (quoted heredocs) so a `curl … | bash` with
  // NO surrounding dir can reconstruct the whole plugin. So render the payload first, then compile
  // install.sh from it.
  const payload: RenderedFile[] = [
    { path: ".claude-plugin/plugin.json", mode: 0o644, content: renderPluginJson(agentId, version, caps) },
    { path: ".claude-plugin/marketplace.json", mode: 0o644, content: renderMarketplaceJson(agentId) },
    { path: `skills/${SKILL_NAME}/SKILL.md`, mode: 0o644, content: renderSkill(agentId, caps, skillBody) },
    { path: "bin/plexus", mode: 0o755, content: engine },
    // The per-agent, collision-proof launcher (`bin/plexus-<agentId>`) — the command the SKILL
    // teaches. A sibling of the engine; execs it directly (never a PATH lookup) so a global
    // `plexus` can never intercept the call. See `renderLauncher`.
    { path: `bin/${launcherCommand(agentId)}`, mode: 0o755, content: renderLauncher(agentId) },
    { path: "README.md", mode: 0o644, content: renderReadme(agentId, version, caps) },
  ];

  // Stable file order (install.sh sits where it always did — before README), preserving the
  // paths[] the tests assert. install.sh materializes `payload` into a stable dir at run time.
  const files: RenderedFile[] = [
    payload[0]!, // .claude-plugin/plugin.json
    payload[1]!, // .claude-plugin/marketplace.json
    payload[2]!, // skills/use-plexus/SKILL.md
    payload[3]!, // bin/plexus
    payload[4]!, // bin/plexus-<agentId> (the per-agent launcher)
    { path: "install.sh", mode: 0o755, content: renderInstallSh(agentId, gatewayBaseUrl, payload) },
    payload[5]!, // README.md
  ];

  return {
    dirName,
    pluginName: PLUGIN_NAME,
    marketplaceName: MARKETPLACE_NAME,
    version,
    files,
    installCommand: renderInstallCommand(agentId, gatewayBaseUrl, code),
  };
}

/**
 * Materialize a rendered plugin to `destDir/<dirName>` (creating parents), applying each
 * file's POSIX mode. Returns the absolute plugin-root path (what `claude plugin
 * marketplace add` wants). Writing is a thin, deterministic side-effect over `renderPlugin`.
 */
export function writePlugin(input: RenderPluginInput, destDir: string): { root: string; rendered: RenderedPlugin } {
  const rendered = renderPlugin(input);
  const root = join(destDir, rendered.dirName);
  for (const f of rendered.files) {
    const abs = join(root, f.path);
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, f.content);
    try {
      chmodSync(abs, f.mode);
    } catch {
      /* best-effort on platforms without chmod */
    }
  }
  return { root, rendered };
}

// ── Cap-set resolution (Inv II: only Floor-advertised caps) ────────────────────────────

interface ResolvedCap {
  id: string;
  label: string;
  summary: string;
  grants: string[];
  provenance?: string;
  sensitivity?: string;
}

function resolveCaps(advertised: CapabilitySummary[], requested: CapabilityId[]): ResolvedCap[] {
  const byId = new Map(advertised.map((c) => [c.id, c]));
  const unknown = requested.filter((id) => !byId.has(id));
  if (unknown.length > 0) {
    throw new Error(
      `renderPlugin: capability id(s) not advertised by the Floor: ${unknown.join(", ")}. ` +
        `A compiled skill may reference ONLY caps the gateway advertises (Inv II).`,
    );
  }
  // De-dupe + sort by id → deterministic ordering regardless of caller order.
  const ids = [...new Set(requested)].sort();
  return ids.map((id) => {
    const c = byId.get(id)!;
    return {
      id: c.id,
      label: c.label,
      summary: c.summary,
      grants: [...(c.grants ?? [])],
      ...(c.provenance ? { provenance: c.provenance } : {}),
      ...(c.sensitivity ? { sensitivity: c.sensitivity } : {}),
    };
  });
}

// ── [T] plugin.json ────────────────────────────────────────────────────────────────────

function renderPluginJson(agentId: string, version: string, caps: ResolvedCap[]): string {
  const capList = caps.map((c) => c.id).join(", ");
  const doc = {
    name: PLUGIN_NAME,
    version,
    displayName: `Plexus (agent ${agentId})`,
    description:
      `Call the local Plexus capabilities granted to agent '${agentId}' via the plugin's own bundled ` +
      `\`${launcherCommand(agentId)}\` command on PATH` +
      (capList ? `: ${capList}. ` : ". ") +
      `Use when a task needs a capability that lives on this machine.`,
    author: { name: AUTHOR_NAME },
  };
  return stableJson(doc);
}

// ── [T] marketplace.json (makes the dir a one-plugin marketplace — D3) ──────────────────

function renderMarketplaceJson(agentId: string): string {
  const doc = {
    name: MARKETPLACE_NAME,
    owner: { name: AUTHOR_NAME },
    plugins: [
      {
        name: PLUGIN_NAME,
        source: "./",
        description: `Plexus local-capability access compiled for agent '${agentId}'.`,
      },
    ],
  };
  return stableJson(doc);
}

// ── [P]+[T] SKILL.md — templated frontmatter + cap header, prose body verbatim ──────────

function renderSkill(agentId: string, caps: ResolvedCap[], body: string): string {
  // The plugin's OWN bundled launcher command (`plexus-<agentId>`). This is the ONE per-agent
  // bit the SKILL teaches as a runnable command; it lives ONLY in this TEMPLATED region (never in
  // the hash-pinned [P] body), so the body stays agent-agnostic while the artifact still teaches
  // the collision-proof command with the real agentId filled in. See `launcherCommand`.
  const cmd = launcherCommand(agentId);

  // tier-1: the always-in-context `description`. References ONLY granted caps + the launcher.
  const capNames = caps.map((c) => c.id).join(", ");
  const description =
    `Use the user's local Plexus capability gateway to call the capabilities granted to this ` +
    `agent — ${capNames || "the granted capabilities"} — through this plugin's own bundled ` +
    `\`${cmd}\` command on the Bash PATH. Use when the user asks to use a local app/tool or when a ` +
    `task needs a capability that lives on THIS machine rather than the open web. Discover what you ` +
    `can call now with \`${cmd} list\`, then call a capability directly with ` +
    `\`${cmd} <capabilityId> <args...>\`; the credential and auth are already handled. \`${cmd}\` is your ` +
    `ONLY interface — never hand-roll HTTP or guess auth.`;

  const frontmatter = [
    "---",
    `name: ${SKILL_NAME}`,
    "description: >",
    ...wrap(description, 76).map((l) => `  ${l}`),
    "allowed-tools: Bash",
    "---",
  ].join("\n");

  // tier-2 header [T]: who you are + the granted-cap quick-list, filled from the Floor.
  const capLines =
    caps.length > 0
      ? caps
          .map((c) => {
            const verbs = c.grants.length ? c.grants.join("/") : "—";
            const posture = [c.provenance, c.sensitivity].filter(Boolean).join(", ");
            const tail = posture ? ` _(${posture})_` : "";
            return `- \`${c.id}\` — ${c.label} (${verbs})${tail}`;
          })
          .join("\n")
      : "_(no capabilities were selected for this integration)_";

  const header = [
    `# Use Plexus — capabilities granted to agent \`${agentId}\``,
    "",
    "You are enrolled with Plexus as agent " +
      `\`${agentId}\`; your credential is stored locally (0600) and you never handle it.`,
    "You have standing, admin-approved grants for these capabilities:",
    "",
    capLines,
    "",
    "Call any of them by id — see below.",
    "",
    // tier-2 command block [T] — the per-agent, collision-proof launcher (with the REAL agentId).
    // This is the ONLY command the agent should type; it is version-pinned to THIS plugin and
    // bound to this agent's identity. It MUST live here (templated), not in the [P] body below.
    "## How to call — use this plugin's OWN bundled command",
    "",
    `Call any granted capability with **\`${cmd}\`** — the bundled, version-pinned launcher this ` +
      `plugin puts on your Bash PATH. Its unique per-agent name means it is never shadowed by a ` +
      `global \`plexus\` (a different project may run a different Plexus version) or another ` +
      `plugin, and it runs THIS plugin's own engine as \`${agentId}\`. Never type a bare \`plexus\` — ` +
      `always \`${cmd}\`. Everything below runs as Bash:`,
    "",
    "```bash",
    `${cmd} list                              # DISCOVER: what you can call now + what needs approval`,
    `${cmd} <capabilityId> <args...>          # positional args bind to the input schema, in order`,
    `${cmd} <capabilityId> key=value ...      # or name the input fields`,
    `${cmd} <capabilityId> --input '<json>'   # or pass full JSON input`,
    `${cmd} <capabilityId> --json             # print the raw InvokeResponse to parse`,
    "```",
    "",
    `**\`${cmd}\` is your ONLY interface to Plexus** — discover (\`list\`), inspect, and invoke are all ` +
      `subcommands of it. Never construct raw HTTP requests to the gateway, never run enroll/handshake/` +
      `manifest yourself, and never guess at authentication — the command handles your credential for you. ` +
      `To see newly-exposed capabilities, run \`${cmd} list\` (don't hand-roll HTTP to discover).`,
    "",
    "On success you get the **real result** on stdout — and *only* the result; the auth plumbing " +
      "stays hidden inside the binary. Use `--json` whenever you need to parse the output.",
    "",
    `If you are ever **not yet enrolled** (a fresh machine, or your credential was reset), run ` +
      `\`${cmd} enroll <one-time-code>\` with the code your administrator gave you — that is the ` +
      `only time a code is involved. **Never** invent, forge, or reuse another credential.`,
    "",
  ].join("\n");

  return `${frontmatter}\n\n${header}${body.replace(/^<!--[\s\S]*?-->\n*/, "")}`;
}

// ── [T] install.sh — the SELF-CONTAINED one-command installer (curl … | bash safe) ──────

/**
 * Render the self-contained bootstrap installer. Unlike a plugin script that assumes it runs
 * from inside a materialized dir, THIS installer is meant to be piped: `curl -fsSL <gw>/
 * integration/<agent>/install.sh | PLEXUS_ENROLL_CODE=… bash`, where there is NO surrounding
 * directory and NO `bin/plexus` on disk yet. So it:
 *   1. picks a STABLE plugin dir (`${PLEXUS_HOME:-$HOME/.plexus}/plugins/plexus@<agentId>/`),
 *   2. writes EVERY payload file into it from INLINE quoted heredocs (byte-for-byte; `<<'EOF'`
 *      so nothing shell-interpolates — safe for the ~500-line JS engine + multi-line prose),
 *   3. pins the gateway, redeems the one-time code (rides $PLEXUS_ENROLL_CODE, NEVER baked),
 *   4. and — when `claude` is present — registers + installs the plugin against THAT dir.
 *
 * Deterministic + secret-FREE (Inv III/VI): the inlined payload is exactly the payload files
 * (which the verifier already proves carry no PAT/code/connection-key); the one-time code and
 * the durable PAT are never written here. Same inputs → byte-identical script (modulo the
 * compile stamp that rides plugin.json/README the payload embeds).
 */
function renderInstallSh(agentId: string, gatewayBaseUrl: string, payload: RenderedFile[]): string {
  const L: string[] = [];

  L.push(
    "#!/usr/bin/env bash",
    `# Plexus Claude Code plugin installer — compiled for agent '${agentId}'.`,
    "#",
    "# SELF-CONTAINED bootstrap — safe under:",
    "#   curl -fsSL <gateway>/integration/<agentId>/install.sh | PLEXUS_ENROLL_CODE=... bash",
    "# with NO surrounding directory. It materializes the WHOLE plugin from inline heredocs into a",
    "# stable dir, pins the gateway, redeems the one-time code that rides $PLEXUS_ENROLL_CODE (NEVER",
    "# baked into this file), and — when the 'claude' CLI is present — registers + installs the",
    "# plugin. Deterministic + secret-free (Inv III/VI): no PAT, no code, no key is ever written here.",
    "set -euo pipefail",
    "",
    `AGENT_ID=${shSingleQuote(agentId)}`,
    `PLUGIN_NAME=${shSingleQuote(PLUGIN_NAME)}`,
    `MARKETPLACE=${shSingleQuote(MARKETPLACE_NAME)}`,
    // Bind the baked default to a SINGLE-QUOTED var (inert — no command-substitution), then use it
    // as the `${PLEXUS_GATEWAY:-…}` default: a gatewayBaseUrl with shell metacharacters cannot inject.
    `PLEXUS_GATEWAY_DEFAULT=${shSingleQuote(gatewayBaseUrl)}`,
    'PLEXUS_GATEWAY="${PLEXUS_GATEWAY:-$PLEXUS_GATEWAY_DEFAULT}"',
    'PLEXUS_HOME="${PLEXUS_HOME:-$HOME/.plexus}"',
    'DIR="$PLEXUS_HOME/plugins/$PLUGIN_NAME@$AGENT_ID"',
    "",
    "# 1. Materialize the plugin dir from inline heredocs (self-contained; no source dir needed).",
    'mkdir -p "$DIR"',
    'chmod 700 "$PLEXUS_HOME" 2>/dev/null || true',
    "",
  );

  for (const f of payload) {
    const delim = heredocDelim(f.path);
    const body = stripOneTrailingNewline(f.content);
    assertNoHeredocCollision(body, delim, f.path);
    const parent = parentDirOf(f.path);
    if (parent) L.push(`mkdir -p "$DIR/${parent}"`);
    L.push(`cat > "$DIR/${f.path}" <<'${delim}'`);
    L.push(body);
    L.push(delim);
    L.push(`chmod ${f.mode.toString(8)} "$DIR/${f.path}"`);
    L.push("");
  }

  L.push(
    "# 2. Pin the gateway for the CLI engine so 'plexus <cap>' reaches the right port.",
    'mkdir -p "$PLEXUS_HOME/agents"',
    `printf '%s\\n' "$PLEXUS_GATEWAY" > "$PLEXUS_HOME/gateway"`,
    "",
    "# 3. Enroll: redeem the one-time code -> durable PAT. Runs FIRST (useful with or without",
    "#    Claude Code); the code never enters the agent's context.",
    'if [ -n "${PLEXUS_ENROLL_CODE:-}" ]; then',
    '  SCRATCH="$PLEXUS_HOME/agents/$AGENT_ID.enroll"',
    `  ( umask 177; printf '%s' "$PLEXUS_ENROLL_CODE" > "$SCRATCH" )   # 0600 scratch, code only`,
    '  RUNTIME=""',
    '  if command -v node >/dev/null 2>&1; then RUNTIME="node"; elif command -v bun >/dev/null 2>&1; then RUNTIME="bun"; fi',
    '  if [ -n "$RUNTIME" ]; then',
    '    if PLEXUS_HOME="$PLEXUS_HOME" PLEXUS_GATEWAY="$PLEXUS_GATEWAY" "$RUNTIME" "$DIR/bin/plexus" enroll "$(cat "$SCRATCH")"; then',
    '      rm -f "$SCRATCH"   # code consumed server-side; drop the on-disk copy',
    `      echo "plexus install: enrolled agent '$AGENT_ID'."`,
    "    else",
    '      echo "plexus install: enrollment did not complete; your one-time code is at $SCRATCH (0600). Re-run: plexus enroll \\"\\$(cat $SCRATCH)\\"" >&2',
    "    fi",
    "  else",
    '    echo "plexus install: no node/bun runtime found to redeem now; the one-time code is saved at $SCRATCH (0600)." >&2',
    "  fi",
    "else",
    '  echo "plexus install: no \\$PLEXUS_ENROLL_CODE supplied; skipping enrollment. Ask your administrator for a one-time code, then run: plexus enroll <code>." >&2',
    "fi",
    "",
    "# 4. Register this artifact as a one-plugin marketplace + install it (idempotent). Optional:",
    "#    the gateway pin + files + enrollment above already make 'plexus <cap>' work; this step",
    "#    just wires the SKILL into Claude Code, so it is SKIPPED (not fatal) when 'claude' is absent.",
    "if command -v claude >/dev/null 2>&1; then",
    '  if ! claude plugin marketplace add "$DIR" 2>/dev/null; then',
    '    claude plugin marketplace update "$MARKETPLACE" 2>/dev/null || true',
    "  fi",
    '  if ! claude plugin install "$PLUGIN_NAME@$MARKETPLACE" --scope user 2>/dev/null; then',
    '    claude plugin update "$PLUGIN_NAME@$MARKETPLACE" 2>/dev/null || true',
    "  fi",
    '  echo "plexus install: registered the plugin with Claude Code. Start a NEW session (or /reload-plugins) to activate."',
    "else",
    `  echo "plexus install: the 'claude' CLI was not found — the gateway pin, plugin files, and enrollment are ready at $DIR." >&2`,
    '  echo "plexus install: install Claude Code (>= v2.1.195), then run: claude plugin marketplace add \\"$DIR\\" && claude plugin install \\"$PLUGIN_NAME@$MARKETPLACE\\" --scope user" >&2',
    "fi",
    "",
    'echo "plexus install: done."',
  );

  return L.join("\n") + "\n";
}

// ── [T] bin/plexus-<agentId> — the per-agent, collision-proof launcher ───────────────────

/**
 * Render the per-agent launcher (`bin/plexus-<agentId>`). It is the ONE command the SKILL teaches.
 * WHY it exists (Bug B): a bare `plexus` on the Bash PATH is resolved by PATH order, so a global
 * `plexus` (a different project's / a different Plexus VERSION's binary) can shadow the plugin's
 * own engine and authenticate as the WRONG agent. This launcher fixes that STRUCTURALLY:
 *   • its name is UNIQUE per agentId → no global `plexus` or other plugin can ever shadow it;
 *   • it execs THIS plugin's OWN sibling engine (`bin/plexus`) by a path relative to itself
 *     (`$SELF_DIR/plexus`), never a PATH lookup → always this plugin's version, never a global one;
 *   • it exports `PLEXUS_AGENT_ID=<agentId>` → the engine picks THIS agent's PAT unambiguously,
 *     never failing over to another agent's stored credential.
 * It picks node|bun the SAME way install.sh does. Deterministic + secret-free (no PAT/code/key).
 */
function renderLauncher(agentId: string): string {
  const cmd = launcherCommand(agentId);
  return (
    [
      "#!/usr/bin/env bash",
      `# Plexus launcher for agent '${agentId}' — this plugin's OWN bundled, version-pinned engine.`,
      "# UNIQUE per-agent name so no global 'plexus' (or other plugin) can shadow it. Resolves its",
      "# own dir and execs the SIBLING engine by that path (never a PATH lookup), pinned to this",
      "# agent via PLEXUS_AGENT_ID. Deterministic + secret-free (no PAT, no code, no key).",
      "set -euo pipefail",
      'SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"',
      'RUNTIME=""',
      'if command -v node >/dev/null 2>&1; then RUNTIME="node"; elif command -v bun >/dev/null 2>&1; then RUNTIME="bun"; fi',
      'if [ -z "$RUNTIME" ]; then',
      `  echo "${cmd}: no node or bun runtime found on PATH to run the bundled engine." >&2`,
      "  exit 127",
      "fi",
      `export PLEXUS_AGENT_ID=${shSingleQuote(agentId)}`,
      'exec "$RUNTIME" "$SELF_DIR/plexus" "$@"',
      "",
    ].join("\n")
  );
}

/** The parent dir of a plugin-relative path (`""` for a top-level file). */
function parentDirOf(p: string): string {
  const i = p.lastIndexOf("/");
  return i >= 0 ? p.slice(0, i) : "";
}

/** A fixed, collision-proof heredoc terminator per payload path (deterministic). */
function heredocDelim(path: string): string {
  return "PLEXUS_EOF_" + path.replace(/[^A-Za-z0-9]+/g, "_").toUpperCase();
}

// ── The copy-able one-command install string (carries the code via env, ADR-8) ──────────

function renderInstallCommand(agentId: string, gatewayBaseUrl: string, code: string): string {
  // The endpoint path is D1-ENDPOINT's to serve; this is the canonical shape. The code
  // rides in an ENV var on the piped `bash` — NOT inside any distributed file.
  return (
    `curl -fsSL ${gatewayBaseUrl}/integration/${agentId}/install.sh` +
    ` | PLEXUS_ENROLL_CODE="${code}" bash`
  );
}

// ── [S] README (human doc — NOT loaded as CC context, D1) ───────────────────────────────

function renderReadme(agentId: string, version: string, caps: ResolvedCap[]): string {
  const capLines = caps.length
    ? caps.map((c) => `- \`${c.id}\` — ${c.label} (${c.grants.join("/") || "—"})`).join("\n")
    : "_(none selected)_";
  const cmd = launcherCommand(agentId);
  return `# Plexus for Claude Code — agent \`${agentId}\`

A Claude Code plugin compiled by Plexus that lets this agent call the local capabilities
it has been granted, via this plugin's OWN bundled \`${cmd}\` command on the Bash PATH
(a version-pinned launcher unique to this agent — never a global \`plexus\`). Compiled
version \`${version}\`.

This directory is a self-hosting one-plugin marketplace. Install it with the one-command
installer your admin console shows (it carries your one-time enrollment code):

\`\`\`bash
curl -fsSL <gateway>/integration/${agentId}/install.sh | PLEXUS_ENROLL_CODE="<code>" bash
\`\`\`

or manually:

\`\`\`bash
claude plugin marketplace add "$(pwd)"
claude plugin install ${PLUGIN_NAME}@${MARKETPLACE_NAME} --scope user
\`\`\`

## Granted capabilities

${capLines}

Run \`${cmd} list\` to discover what you can call right now (and what still needs the owner's
approval) — including any capabilities exposed after this plugin was compiled. \`${cmd}\` is the
agent's ONLY interface: discover, inspect, and invoke are all subcommands of it; the auth is
hidden, so never hand-roll HTTP or guess a credential.

Plexus is **not** an MCP server; this plugin integrates via a SKILL (teach) + a \`bin/\`
executable on PATH (run). The auth chain (enroll -> PAT -> handshake -> token -> invoke)
lives entirely inside \`bin/plexus\` and never enters the agent's context.
`;
}

// ── Small deterministic helpers ─────────────────────────────────────────────────────────

/** Stable JSON — fixed 2-space indent + trailing newline, key order as authored. */
function stableJson(value: unknown): string {
  return JSON.stringify(value, null, 2) + "\n";
}

/** Derive a valid, monotonic-ish semver from an arbitrary stamp (the plugin cache key). */
function versionFromStamp(stamp: string): string {
  const digits = stamp.replace(/[^0-9]/g, "");
  const tag = digits.length ? digits : "0";
  return `0.1.0-c${tag}`;
}

/** Deterministic word-wrap for the YAML folded `description` block. */
function wrap(text: string, width: number): string[] {
  const words = text.split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let cur = "";
  for (const w of words) {
    if (cur.length === 0) cur = w;
    else if (cur.length + 1 + w.length <= width) cur += " " + w;
    else {
      lines.push(cur);
      cur = w;
    }
  }
  if (cur.length) lines.push(cur);
  return lines.length ? lines : [""];
}
