/**
 * G1-TEMPLATE — the deterministic CC-plugin renderer (the "compiler").
 *
 * SSOT: docs/design/agent-skill-compile-domain-model.md §4 (the compiled artifact,
 *       3-tier progressive disclosure) + Inv II (additive projection over the Floor)
 *       + Inv VI (auth/invoke core deterministically TEMPLATED, never LLM-authored),
 *       ADR-6/ADR-8; and docs/design/cc-plugin-artifact-spec.md §1/§2/§3/§5.
 *
 * WHAT THIS IS — a pure, deterministic function (NO LLM, no network, no clock unless
 * you let it) that projects a *granted cap-set* into a ready-to-install Claude Code
 * plugin directory. Given the same (Floor + capabilityIds + agentId + code +
 * compileStamp) it emits BYTE-IDENTICAL files. It is `renderPlugin()` (returns the
 * files in memory) + `writePlugin()` (materializes them to a dir, with modes). D1-
 * ENDPOINT imports this to serve `GET /integration/<agent>`.
 *
 * THE SKELETON IT EMITS (annotated per cc-plugin-artifact-spec §5):
 *
 *   plexus@<agentId>/                       # a self-hosting one-plugin marketplace
 *   ├── .claude-plugin/
 *   │   ├── plugin.json          [T]        # identity; version = compile stamp (cache key, ADR-10)
 *   │   └── marketplace.json     [T]        # makes the dir `claude plugin marketplace add`-able
 *   ├── skills/use-plexus/
 *   │   └── SKILL.md             [P]+[T]    # tier-1 frontmatter [T] + tier-2 prose body [P]
 *   ├── bin/
 *   │   └── plexus               [S]        # tier-3: G2 engine VERBATIM (auth core, never in context)
 *   ├── install.sh               [T]        # one-command install; code rides via env->0600 scratch
 *   └── README.md                [S]        # human doc (NOT loaded as CC context — D1)
 *
 * INV VI (templated auth core, never LLM-authored) — the entire redeem->PAT->
 * handshake->token->invoke chain is `bin/plexus`, which is the COMMITTED, Floor-driven
 * G2 engine copied BYTE-FOR-BYTE (see `readEngine()`), plus the templated `install.sh`
 * whose enrollment step invokes that same engine. No prose file carries auth mechanics;
 * the SKILL body [P] is pedagogy only. Nothing here is generated by a model.
 *
 * INV III / secret hygiene — NO long-lived secret is ever written into the artifact.
 * The durable PAT never appears. The one-time enrollment code is NOT baked into any
 * emitted file; it rides the *install command string* (returned separately) in an env
 * var, which `install.sh` lands in a 0600 scratch file, redeems, then deletes.
 */

import { fileURLToPath } from "node:url";
import { readFileSync, mkdirSync, writeFileSync, chmodSync } from "node:fs";
import { join, dirname } from "node:path";

import type { WellKnownDocument, CapabilitySummary, CapabilityId } from "@plexus/protocol";

// ── Fixed identity constants (kebab-case; the skill namespace + install target) ──────
// The plugin NAME stays the stable "plexus" so the skill is `/plexus:use-plexus` and the
// verified install command is `plexus@plexus` (`<plugin>@<marketplace>`). Per-agent
// identity is carried by the DIRECTORY name (plexus@<agentId>), the version (compile
// stamp), and the description — NOT by the plugin name (an `@` in the name would break
// `claude plugin install <plugin>@<marketplace>` parsing). See cc-plugin-artifact-spec §5.
const PLUGIN_NAME = "plexus";
const MARKETPLACE_NAME = "plexus";
const SKILL_NAME = "use-plexus";
const AUTHOR_NAME = "Plexus";

// The G2 engine SSOT — copied verbatim into the artifact's `bin/plexus` (tier-3). Resolved
// relative to this module the same way the runtime references its other repo assets
// (see core/admin.ts). Overridable for tests.
const ENGINE_SOURCE = fileURLToPath(new URL("../../../../tools/plexus-cli/plexus", import.meta.url));
// The hand-authored [P] prose body of the SKILL (same for every integration).
const SKILL_BODY_SOURCE = fileURLToPath(new URL("./templates/skill-body.md", import.meta.url));

// ── Public API ───────────────────────────────────────────────────────────────────────

/** Inputs to the renderer — the Floor + a selected cap-set + who + the bootstrap code. */
export interface RenderPluginInput {
  /** The gateway's Floor: `GET /.well-known/plexus`. Source of gateway URL + cap metadata. */
  floor: WellKnownDocument;
  /**
   * The selected (granted) cap-set to project — capability ids. MUST be a subset of the
   * Floor's advertised capabilities (a cap the Floor does not advertise cannot be granted
   * or referenced). Order is irrelevant; the renderer sorts for determinism.
   */
  capabilityIds: CapabilityId[];
  /** The agent this integration is compiled for (the enrollment/PAT identity). */
  agentId: string;
  /** The one-time enrollment code (`plx_enroll_…`). Rides the install command, never a file. */
  enrollmentCode: string;
  /**
   * The compile timestamp — the ONLY intentional source of non-determinism, injected so
   * tests are stable. Any ISO-ish string; defaults to now. Drives the plugin `version`
   * (the cache key, ADR-10) so a regenerated artifact is seen as a new version.
   */
  compileStamp?: string;
  /** Override the G2 engine source path (tests only). Defaults to `tools/plexus-cli/plexus`. */
  enginePath?: string;
  /** Override the [P] skill-body source path (tests only). */
  skillBodyPath?: string;
}

/** One emitted file, with its POSIX mode (executables are 0o755, the rest 0o644). */
export interface RenderedFile {
  /** Path relative to the plugin root (e.g. `.claude-plugin/plugin.json`). */
  path: string;
  content: string;
  mode: number;
}

/** The rendered artifact — files in memory + the copy-able install command carrying the code. */
export interface RenderedPlugin {
  /** The artifact directory name (`plexus@<agentId>`). */
  dirName: string;
  /** The plugin name field (`plexus`) — the skill namespace + install target. */
  pluginName: string;
  /** The marketplace name (`plexus`). */
  marketplaceName: string;
  /** The plugin version = the compile stamp (the cache key). */
  version: string;
  /** All emitted files, in a deterministic order. */
  files: RenderedFile[];
  /**
   * The copy-able ONE-COMMAND install string the admin console shows (ADR-8). It carries
   * the one-time code in an ENV var (never baked into an artifact file). D1-ENDPOINT may
   * adapt the URL; the shape is `curl … | PLEXUS_ENROLL_CODE=… bash`.
   */
  installCommand: string;
}

/**
 * Render the plugin artifact deterministically. Pure w.r.t. its inputs (given a
 * `compileStamp`, the output is byte-identical across runs, machines, and clocks).
 */
export function renderPlugin(input: RenderPluginInput): RenderedPlugin {
  const agentId = requireNonEmpty(input.agentId, "agentId");
  const code = requireNonEmpty(input.enrollmentCode, "enrollmentCode");
  const stamp = input.compileStamp ?? new Date().toISOString();
  const version = versionFromStamp(stamp);
  const gatewayBaseUrl = stripSlash(input.floor?.gateway?.baseUrl || "");
  if (!gatewayBaseUrl) throw new Error("renderPlugin: floor.gateway.baseUrl is required");

  // Resolve the selected cap-set against the Floor. Every requested id MUST be advertised
  // (Inv II: a skill references ONLY caps the Floor knows — the build-time verifier's core
  // guarantee, enforced here by construction). Sorted by id for a stable ordering.
  const caps = resolveCaps(input.floor.capabilities ?? [], input.capabilityIds);

  const dirName = `${PLUGIN_NAME}@${agentId}`;

  const engine = readFileSync(input.enginePath ?? ENGINE_SOURCE, "utf8");
  const skillBody = readFileSync(input.skillBodyPath ?? SKILL_BODY_SOURCE, "utf8");

  const files: RenderedFile[] = [
    { path: ".claude-plugin/plugin.json", mode: 0o644, content: renderPluginJson(agentId, version, caps) },
    { path: ".claude-plugin/marketplace.json", mode: 0o644, content: renderMarketplaceJson(agentId) },
    { path: `skills/${SKILL_NAME}/SKILL.md`, mode: 0o644, content: renderSkill(agentId, caps, skillBody) },
    { path: "bin/plexus", mode: 0o755, content: engine },
    { path: "install.sh", mode: 0o755, content: renderInstallSh(agentId, gatewayBaseUrl) },
    { path: "README.md", mode: 0o644, content: renderReadme(agentId, version, caps) },
  ];

  return {
    dirName,
    pluginName: PLUGIN_NAME,
    marketplaceName: MARKETPLACE_NAME,
    version,
    files,
    installCommand: renderInstallCommand(agentId, gatewayBaseUrl, code),
  };
}

/**
 * Materialize a rendered plugin to `destDir/<dirName>` (creating parents), applying each
 * file's POSIX mode. Returns the absolute plugin-root path (what `claude plugin
 * marketplace add` wants). Writing is a thin, deterministic side-effect over `renderPlugin`.
 */
export function writePlugin(input: RenderPluginInput, destDir: string): { root: string; rendered: RenderedPlugin } {
  const rendered = renderPlugin(input);
  const root = join(destDir, rendered.dirName);
  for (const f of rendered.files) {
    const abs = join(root, f.path);
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, f.content);
    try {
      chmodSync(abs, f.mode);
    } catch {
      /* best-effort on platforms without chmod */
    }
  }
  return { root, rendered };
}

// ── Cap-set resolution (Inv II: only Floor-advertised caps) ────────────────────────────

interface ResolvedCap {
  id: string;
  label: string;
  summary: string;
  grants: string[];
  provenance?: string;
  sensitivity?: string;
}

function resolveCaps(advertised: CapabilitySummary[], requested: CapabilityId[]): ResolvedCap[] {
  const byId = new Map(advertised.map((c) => [c.id, c]));
  const unknown = requested.filter((id) => !byId.has(id));
  if (unknown.length > 0) {
    throw new Error(
      `renderPlugin: capability id(s) not advertised by the Floor: ${unknown.join(", ")}. ` +
        `A compiled skill may reference ONLY caps the gateway advertises (Inv II).`,
    );
  }
  // De-dupe + sort by id → deterministic ordering regardless of caller order.
  const ids = [...new Set(requested)].sort();
  return ids.map((id) => {
    const c = byId.get(id)!;
    return {
      id: c.id,
      label: c.label,
      summary: c.summary,
      grants: [...(c.grants ?? [])],
      ...(c.provenance ? { provenance: c.provenance } : {}),
      ...(c.sensitivity ? { sensitivity: c.sensitivity } : {}),
    };
  });
}

// ── [T] plugin.json ────────────────────────────────────────────────────────────────────

function renderPluginJson(agentId: string, version: string, caps: ResolvedCap[]): string {
  const capList = caps.map((c) => c.id).join(", ");
  const doc = {
    name: PLUGIN_NAME,
    version,
    displayName: `Plexus (agent ${agentId})`,
    description:
      `Call the local Plexus capabilities granted to agent '${agentId}' via the \`plexus\` CLI on PATH` +
      (capList ? `: ${capList}. ` : ". ") +
      `Use when a task needs a capability that lives on this machine.`,
    author: { name: AUTHOR_NAME },
  };
  return stableJson(doc);
}

// ── [T] marketplace.json (makes the dir a one-plugin marketplace — D3) ──────────────────

function renderMarketplaceJson(agentId: string): string {
  const doc = {
    name: MARKETPLACE_NAME,
    owner: { name: AUTHOR_NAME },
    plugins: [
      {
        name: PLUGIN_NAME,
        source: "./",
        description: `Plexus local-capability access compiled for agent '${agentId}'.`,
      },
    ],
  };
  return stableJson(doc);
}

// ── [P]+[T] SKILL.md — templated frontmatter + cap header, prose body verbatim ──────────

function renderSkill(agentId: string, caps: ResolvedCap[], body: string): string {
  // tier-1: the always-in-context `description`. References ONLY granted caps.
  const capNames = caps.map((c) => c.id).join(", ");
  const description =
    `Use the user's local Plexus capability gateway to call the capabilities granted to this ` +
    `agent — ${capNames || "the granted capabilities"} — through the \`plexus\` CLI on the Bash ` +
    `PATH. Use when the user asks to use a local app/tool or when a task needs a capability that ` +
    `lives on THIS machine rather than the open web. Call a capability directly with ` +
    `\`plexus <capabilityId> <args...>\`; the credential and auth are already handled.`;

  const frontmatter = [
    "---",
    `name: ${SKILL_NAME}`,
    "description: >",
    ...wrap(description, 76).map((l) => `  ${l}`),
    "allowed-tools: Bash",
    "---",
  ].join("\n");

  // tier-2 header [T]: who you are + the granted-cap quick-list, filled from the Floor.
  const capLines =
    caps.length > 0
      ? caps
          .map((c) => {
            const verbs = c.grants.length ? c.grants.join("/") : "—";
            const posture = [c.provenance, c.sensitivity].filter(Boolean).join(", ");
            const tail = posture ? ` _(${posture})_` : "";
            return `- \`${c.id}\` — ${c.label} (${verbs})${tail}`;
          })
          .join("\n")
      : "_(no capabilities were selected for this integration)_";

  const header = [
    `# Use Plexus — capabilities granted to agent \`${agentId}\``,
    "",
    "You are enrolled with Plexus as agent " +
      `\`${agentId}\`; your credential is stored locally (0600) and you never handle it.`,
    "You have standing, admin-approved grants for these capabilities:",
    "",
    capLines,
    "",
    "Call any of them by id — see below.",
    "",
  ].join("\n");

  return `${frontmatter}\n\n${header}${body.replace(/^<!--[\s\S]*?-->\n*/, "")}`;
}

// ── [T] install.sh — the one-command installer; NO code baked in (rides via env) ────────

function renderInstallSh(agentId: string, gatewayBaseUrl: string): string {
  // NOTE: this file is deterministic and secret-FREE. The one-time code arrives at RUN
  // time via $PLEXUS_ENROLL_CODE (from the copy-able install command), is written to a
  // 0600 scratch file, redeemed via the verbatim engine (Inv VI — templated auth), and
  // then deleted. Enrollment happens in the SHELL context, so the code never enters the
  // agent's context. The whole marketplace-add + install is idempotent (matches cc-master).
  return `#!/usr/bin/env bash
# Plexus Claude Code plugin installer — compiled for agent '${agentId}'.
#
# [T] deterministic + secret-FREE. The one-time enrollment code is NOT in this file; it
# arrives at run time via \$PLEXUS_ENROLL_CODE (see the copy-able one-command install),
# lands in a 0600 scratch file, is redeemed for a durable PAT, then deleted. The durable
# PAT is never written into this artifact (Inv III).
set -euo pipefail

PLUGIN_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
AGENT_ID="${agentId}"
PLUGIN_NAME="${PLUGIN_NAME}"
MARKETPLACE="${MARKETPLACE_NAME}"
PLEXUS_GATEWAY="\${PLEXUS_GATEWAY:-${gatewayBaseUrl}}"
PLEXUS_HOME="\${PLEXUS_HOME:-\$HOME/.plexus}"

# 1. Preflight: the 'claude' CLI must be present for a durable, unattended install.
if ! command -v claude >/dev/null 2>&1; then
  echo "plexus install: the 'claude' CLI is not on PATH — install Claude Code (>= v2.1.195) first." >&2
  exit 127
fi

# 2. Pin the gateway for the CLI engine so 'plexus <cap>' reaches the right port.
mkdir -p "\$PLEXUS_HOME/agents"
chmod 700 "\$PLEXUS_HOME" 2>/dev/null || true
printf '%s\\n' "\$PLEXUS_GATEWAY" > "\$PLEXUS_HOME/gateway"

# 3. Register this artifact as a one-plugin marketplace + install it (idempotent).
if ! claude plugin marketplace add "\$PLUGIN_DIR" 2>/dev/null; then
  claude plugin marketplace update "\$MARKETPLACE" 2>/dev/null || true
fi
if ! claude plugin install "\$PLUGIN_NAME@\$MARKETPLACE" --scope user 2>/dev/null; then
  claude plugin update "\$PLUGIN_NAME@\$MARKETPLACE" 2>/dev/null || true
fi

# 4. Enroll: redeem the one-time code -> durable PAT. The code never enters agent context.
if [ -n "\${PLEXUS_ENROLL_CODE:-}" ]; then
  SCRATCH="\$PLEXUS_HOME/agents/\$AGENT_ID.enroll"
  ( umask 177; printf '%s' "\$PLEXUS_ENROLL_CODE" > "\$SCRATCH" )   # 0600 scratch, code only
  RUNTIME=""
  if command -v node >/dev/null 2>&1; then RUNTIME="node"; elif command -v bun >/dev/null 2>&1; then RUNTIME="bun"; fi
  if [ -n "\$RUNTIME" ]; then
    if PLEXUS_HOME="\$PLEXUS_HOME" PLEXUS_GATEWAY="\$PLEXUS_GATEWAY" "\$RUNTIME" "\$PLUGIN_DIR/bin/plexus" enroll "\$(cat "\$SCRATCH")"; then
      rm -f "\$SCRATCH"   # code consumed server-side; drop the on-disk copy
      echo "plexus install: enrolled agent '\$AGENT_ID'."
    else
      echo "plexus install: enrollment did not complete; your one-time code is at \$SCRATCH (0600). Re-run: plexus enroll \\"\\\$(cat \$SCRATCH)\\"" >&2
    fi
  else
    echo "plexus install: no node/bun runtime found to redeem now; the one-time code is saved at \$SCRATCH (0600)." >&2
  fi
else
  echo "plexus install: no \\\$PLEXUS_ENROLL_CODE supplied; skipping enrollment. Ask your administrator for a one-time code, then run: plexus enroll <code>." >&2
fi

echo "plexus install: done. Start a NEW Claude Code session (or run /reload-plugins) to activate the plugin."
`;
}

// ── The copy-able one-command install string (carries the code via env, ADR-8) ──────────

function renderInstallCommand(agentId: string, gatewayBaseUrl: string, code: string): string {
  // The endpoint path is D1-ENDPOINT's to serve; this is the canonical shape. The code
  // rides in an ENV var on the piped `bash` — NOT inside any distributed file.
  return (
    `curl -fsSL ${gatewayBaseUrl}/integration/${agentId}/install.sh` +
    ` | PLEXUS_ENROLL_CODE="${code}" bash`
  );
}

// ── [S] README (human doc — NOT loaded as CC context, D1) ───────────────────────────────

function renderReadme(agentId: string, version: string, caps: ResolvedCap[]): string {
  const capLines = caps.length
    ? caps.map((c) => `- \`${c.id}\` — ${c.label} (${c.grants.join("/") || "—"})`).join("\n")
    : "_(none selected)_";
  return `# Plexus for Claude Code — agent \`${agentId}\`

A Claude Code plugin compiled by Plexus that lets this agent call the local capabilities
it has been granted, via the \`plexus\` CLI on the Bash PATH. Compiled version \`${version}\`.

This directory is a self-hosting one-plugin marketplace. Install it with the one-command
installer your admin console shows (it carries your one-time enrollment code):

\`\`\`bash
curl -fsSL <gateway>/integration/${agentId}/install.sh | PLEXUS_ENROLL_CODE="<code>" bash
\`\`\`

or manually:

\`\`\`bash
claude plugin marketplace add "$(pwd)"
claude plugin install ${PLUGIN_NAME}@${MARKETPLACE_NAME} --scope user
\`\`\`

## Granted capabilities

${capLines}

Plexus is **not** an MCP server; this plugin integrates via a SKILL (teach) + a \`bin/\`
executable on PATH (run). The auth chain (enroll -> PAT -> handshake -> token -> invoke)
lives entirely inside \`bin/plexus\` and never enters the agent's context.
`;
}

// ── Small deterministic helpers ─────────────────────────────────────────────────────────

/** Stable JSON — fixed 2-space indent + trailing newline, key order as authored. */
function stableJson(value: unknown): string {
  return JSON.stringify(value, null, 2) + "\n";
}

/** Derive a valid, monotonic-ish semver from an arbitrary stamp (the plugin cache key). */
function versionFromStamp(stamp: string): string {
  const digits = stamp.replace(/[^0-9]/g, "");
  const tag = digits.length ? digits : "0";
  return `0.1.0-c${tag}`;
}

function stripSlash(u: string): string {
  return u.replace(/\/+$/, "");
}

function requireNonEmpty(v: string, name: string): string {
  if (typeof v !== "string" || v.trim().length === 0) {
    throw new Error(`renderPlugin: ${name} must be a non-empty string`);
  }
  return v;
}

/** Deterministic word-wrap for the YAML folded `description` block. */
function wrap(text: string, width: number): string[] {
  const words = text.split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let cur = "";
  for (const w of words) {
    if (cur.length === 0) cur = w;
    else if (cur.length + 1 + w.length <= width) cur += " " + w;
    else {
      lines.push(cur);
      cur = w;
    }
  }
  if (cur.length) lines.push(cur);
  return lines.length ? lines : [""];
}
