#!/usr/bin/env bash
#
# setup-tunnel.sh — ONE-TIME prep for the default setup: a NAMED Cloudflare
# Tunnel on YOUR OWN domain, fully CLI-driven (no Zero Trust dashboard needed).
#
#   Prereq (interactive, once): cloudflared tunnel login
#     → opens a browser; pick the zone your hostname lives under. Writes
#       ~/.cloudflared/cert.pem (the tunnel-management credential).
#
#   ./setup-tunnel.sh gw.example.com
#     1. creates (or reuses) the named tunnel `plexus-home-gateway`
#     2. routes gw.example.com → this tunnel (creates the DNS CNAME for you)
#     3. writes $DEMO_ROOT/cloudflared-config.yml with the ingress
#        gw.example.com → http://localhost:7901 (+ a catch-all 404)
#
# After this, `./up.sh --hostname gw.example.com` starts the connector from that
# config every time. Re-runnable: reuses an existing tunnel/route.
set -euo pipefail

DEMO_ROOT="${DEMO_ROOT:-$HOME/PlexusDemo/home-gateway}"
PORT="${PLEXUS_HOME_GATEWAY_PORT:-7901}"
TUNNEL_NAME="${PLEXUS_TUNNEL_NAME:-plexus-home-gateway}"
HOSTNAME_ARG="${1:-}"

die() { echo "[setup-tunnel] ERROR: $*" >&2; exit 1; }
command -v cloudflared >/dev/null || die "cloudflared is required (brew install cloudflared)"
[ -n "$HOSTNAME_ARG" ] || die "usage: ./setup-tunnel.sh gw.<your-domain>"
[ -f "$HOME/.cloudflared/cert.pem" ] || die "no ~/.cloudflared/cert.pem — run \`cloudflared tunnel login\` first (browser; pick your zone)"

mkdir -p "$DEMO_ROOT"

# 1. Create or reuse the named tunnel.
if cloudflared tunnel list 2>/dev/null | awk '{print $2}' | grep -qx "$TUNNEL_NAME"; then
  echo "[setup-tunnel] tunnel '$TUNNEL_NAME' already exists — reusing it"
else
  cloudflared tunnel create "$TUNNEL_NAME"
fi
TUNNEL_ID="$(cloudflared tunnel list 2>/dev/null | awk -v n="$TUNNEL_NAME" '$2==n {print $1}')"
[ -n "$TUNNEL_ID" ] || die "could not resolve the tunnel id for '$TUNNEL_NAME'"

# 2. Route the hostname to it. Idempotent — an existing route to THIS tunnel is fine — but
# a genuine failure (zone not on this account, CNAME owned by another record) must NOT be
# masked into a false "✅ done". Capture output, tolerate only the "already exists" case.
route_out="$(cloudflared tunnel route dns "$TUNNEL_NAME" "$HOSTNAME_ARG" 2>&1)" || route_rc=$?
echo "$route_out" | sed 's/^/[setup-tunnel] /'
if [ "${route_rc:-0}" -ne 0 ] && ! echo "$route_out" | grep -qiE 'already (exists|configured)|record with the same'; then
  die "failed to route $HOSTNAME_ARG to tunnel '$TUNNEL_NAME' (see the cloudflared message above) — is the zone on this Cloudflare account?"
fi

# 3. Write the locally-managed connector config up.sh runs from.
CRED_FILE="$HOME/.cloudflared/$TUNNEL_ID.json"
[ -f "$CRED_FILE" ] || die "credentials file $CRED_FILE not found (tunnel created on another machine?)"
cat > "$DEMO_ROOT/cloudflared-config.yml" << YML
# Generated by setup-tunnel.sh — the home gateway's edge ingress.
tunnel: $TUNNEL_ID
credentials-file: $CRED_FILE
ingress:
  # cloudflared performs the TLS/WebSocket upgrade against an http:// origin.
  - hostname: $HOSTNAME_ARG
    service: http://localhost:$PORT
  # Required catch-all: anything else 404s (never expose the origin broadly).
  - service: http_status:404
YML

cat << SUMMARY
[setup-tunnel] ✅ done.

  tunnel     : $TUNNEL_NAME ($TUNNEL_ID)
  hostname   : https://$HOSTNAME_ARG  →  http://localhost:$PORT
  config     : $DEMO_ROOT/cloudflared-config.yml

Next: ./up.sh --hostname $HOSTNAME_ARG
SUMMARY
